## a_tersor_initialization.py

In [8]:
import torch

# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


### 해석
- torch.Tensor에서 대문자를 사용한 Tensor를 사용 => float32 타입의 텐서를 생성
- device='cpu'를 통해 텐서가 cpu에 저장
- t1.requires_grad의 결과는 PyTorch에서 기본적으로 텐서를 만들 때 자동 미분 기능이 꺼져 있기 때문
- 3개의 요소가 있는 1차원 텐서 => torch.Size([3])
- size()와 shape는 같은 역할을 하므로 결과가 같음
- .cpu()는 텐서의 위치를 cpu로 이동시키는 역할

### 취득한 기술적 사항/고찰 내용
- PyTorch에서 기본적으로 텐서를 만들 때 자동 미분 기능이 같이 존재한다는 사실

In [9]:
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


### 해석
- torch.tensor에서 소문자를 사용한 tensor를 사용 => 데이터 타입을 자동으로 추론
  => [1, 2, 3]은 정수 리스트이므로 int64 형태로 만들어짐
- 나머지는 위의 해석과 같음

### 취득한 기술적 사항/고찰 내용
- torch.tensor과 torch.Tensor의 t의 대문자 여부에 따라 데이터 타입이 달라진다는 사실과 이를 주의깊게 봐야된다는 사실

In [12]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print("a1 =",a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print("a2 =",a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print("a3 =",a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print("a4 =",a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print("a5 =",a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print("a6 =",a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print("a7 =",a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print("a8 =",a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print("a9 =",a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print("a10 =",a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print("a10 =",a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

a1 = torch.Size([]) 0
a2 = torch.Size([1]) 1
a3 = torch.Size([5]) 1
a4 = torch.Size([5, 1]) 2
a5 = torch.Size([3, 2]) 2
a6 = torch.Size([3, 2, 1]) 3
a7 = torch.Size([3, 1, 2, 1]) 4
a8 = torch.Size([3, 1, 2, 3]) 4
a9 = torch.Size([3, 1, 2, 3, 1]) 5
a10 = torch.Size([4, 5]) 2
a10 = torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

### 해석
- .shape는 각 차원의 크기를 알려주며, .ndim은 차원의 개수를 알려준다.
- tensor()안에 []이 들어가지 않은 건 차원이 없다는 것 => 이는 a1의 shape 결과 torch.Size([])로 이어지며 이는 차원이 없다는 것을 의미한다
- 1차원은 dim0, 2차원은 dim1 순으로 숫자가 늘어난다.
- tensor()를 만들 때, 기본적으로 같은 차원에 있는 데이터의 길이가 같아야 한다는 가정으로 생성된다. 그러나 a11은 4번째 차원에서 데이터의 길이가 3, 2로 각각 달라 오류가 발생한다.

### 코드 추가
- 결과의 명확성을 추가하기 위해 print() 안에 코드 일부를 추가했다

### 취득한 기술적 사항/고찰 내용
- tensor()를 만들 때, 기본적으로 같은 차원에 있는 데이터의 길이가 같아야 한다는 가정으로 생성된다는 점

## b_tensor_initialization_copy.py

In [18]:
import torch
import numpy as np

l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print("t1 :",t1)
print("t2 :",t2)
print("t3 :",t3)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print("t4 :",t4)
print("t5 :",t5)
print("t6 :",t6)

t1 : tensor([1., 2., 3.])
t2 : tensor([1, 2, 3])
t3 : tensor([1, 2, 3])
t4 : tensor([1., 2., 3.])
t5 : tensor([1, 2, 3])
t6 : tensor([100,   2,   3])


### 해석
- torch.Tensor()과 torch.tensor() 모두 복사본을 형성하여 텐서를 생성한다. 이는 원본 list 또는 NumPy 배열의 내부 데이터가 바뀌어도 텐서에 영향을 끼치지 않는다는 걸 알려준다.
- as_tensor()은 PyTorch가 NumPy 배열을 감지할 경우 데이터를 공유하지만, 리스트는 공유하지 않고 복사본을 형성한다. t3와 t6의 결과를 보면 이를 알 수 있다.

### 코드 추가
- 결과의 명확성을 추가하기 위해 print() 안에 코드 일부를 추가했다.

### 취득한 기술적 사항/고찰 내용
- NumPy 배열을 사용한 텐서가 as_tensor() 함수를 사용했을 때만 데이터를 공유하고, 나머지 경우의 수는 다 복제본을 생성한다는 점

## c_tensor_initialization_constant_values.py

In [1]:
import torch

t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print("t1 :",t1)  # >>> tensor([1., 1., 1., 1., 1.])
print("t1_like :",t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print("t2 :",t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print("t2_like :",t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print("t3 :",t3)  # >>> tensor([0., 0., 0., 0.])
print("t3_like :",t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)
print("t4 :",t4)

t5 = torch.eye(3,5)
print("t5 :",t5)

t6 = torch.eye(5,3)
print("t6 :",t6)

t1 : tensor([1., 1., 1., 1., 1.])
t1_like : tensor([1., 1., 1., 1., 1.])
t2 : tensor([0., 0., 0., 0., 0., 0.])
t2_like : tensor([0., 0., 0., 0., 0., 0.])
t3 : tensor([4.3024e-22, 1.1603e-42, 0.0000e+00, 0.0000e+00])
t3_like : tensor([0., 0., 0., 0.])
t4 : tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
t5 : tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
t6 : tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


### 해석
- torch.ones()는 텐서의 값을 모두 1.0으로 설정한다.
- torch.zeros()는 텐서의 값을 모두 0.0으로 설정한다.
- torch.empty()는 초기화를 하지 않은 메모리 공간을 그대로 사용하기 때문에 모든 값이 랜덤이다.
- torch.eye(n)는 n*n 단위 행렬을 생성한다. dtype는 기본적으로 float32 형태이다. 대각선에는 1.0, 그 외의 값은 0.0의 값을 가진다.
- torch.eye(n,m)를 통해 n*m 단위 행렬을 생성할 수 있다.
  대각선에는 1.0, 그 외의 값은 0.0의 값을 가지며, 1.0을 가진 값의 개수를 알고 싶다면, n과 m 중 낮은 값을 제시하면 된다.
- size=(n,)는 size=n과 같은 의미를 가진다.
- ones_like(input=x)는 x 텐서와 같은 size와 dtype을 가지면서, 모든 값이 텐서인 1을 생성한다. 다만 새롭게 생성되는 텐서이기 때문에 x와는 다른 독립적인 텐서이다.
- zeros_like(input=x)도 ones_like(input=x)와 역할이 같으며, 모든 값이 텐서인 0을 생성한다는 점만 다르다.
- empty_like(input=x)도 ones_like(input=x)와 역할이 같으며, 모든 값이 랜덤이라는 점만 다르다.

### 코드 추가
- torch.eye()에서 길이가 다른 단위 행렬의 텐서에서 결과값이 어떻게 출력되는지를 이해하기 위해 t5, t6에 관한 코드를 추가했다.
- 결과의 명확성을 추가하기 위해 print() 안에 코드 일부를 추가했다.

### 취득한 기술적 사항/고찰 내용
- torch.eye() 함수를 사용할 때 텐서의 각 차원 크기가 다를 때 1.0의 값의 위치와 개수

## d_tensor_initialization_random_values.py

In [13]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))
print("t1 :",t1)

t2 = torch.rand(size=(1, 3))
print("t2 :",t2)

print("-" * 30)

t2_plus1 = torch.rand(size=(1, 3))*3
print("t2_plus1",t2_plus1)

t2_plus2 = torch.rand(size=(1, 3)) + 2
print("t2_plus2",t2_plus2)

t2_plus3 = torch.rand(size=(1, 3))*3 + 2
print("t2_plus3",t2_plus3)

print("-" * 30)

t3 = torch.randn(size=(1, 3))
print("t3 :",t3)

print("-" * 30)

t3_plus1 = torch.randn(size=(1, 3)) * 4
print("t3_plus1 :",t3_plus1)

t3_plus2 = torch.randn(size=(1, 3)) + 2
print("t3_plus2 :",t3_plus2)

t3_plus3 = torch.randn(size=(1, 3))*4 + 2
print("t3_plus3 :",t3_plus3)

print("-" * 30)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print("t4 :",t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print("t5 :",t5)

print("-" * 30)

t5_plus1 = torch.linspace(start=5.0, end=0.0, steps=3)
print("t5_plus1 :",t5_plus1)

t5_plus2 = torch.linspace(start=5.0, end=5.0, steps=3)
print("t5_plus2 :",t5_plus2)

print("-" * 30)

t6 = torch.arange(5)
print("t6 :",t6)

print("-" * 30)

t6_plus1 = torch.arange(1,5)
print("t6_plus1 :",t6_plus1)

t6_plus2 = torch.arange(5,1,-1)
print("t6_plus2 :",t6_plus2)

print("-" * 30)

print("#" * 30)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print("random1 :",random1)

random2 = torch.rand(2, 3)
print("random2 :",random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print("random3 :",random3)

random4 = torch.rand(2, 3)
print("random4 :",random4)

t1 : tensor([[17, 12]])
t2 : tensor([[0.0453, 0.5035, 0.9978]])
------------------------------
t2_plus1 tensor([[1.1652, 2.0787, 0.5110]])
t2_plus2 tensor([[2.1384, 2.4759, 2.7481]])
t2_plus3 tensor([[2.1084, 3.5187, 4.5408]])
------------------------------
t3 : tensor([[ 0.7500,  0.3572, -1.1860]])
------------------------------
t3_plus1 : tensor([[-1.9487, -7.7143, -4.4621]])
t3_plus2 : tensor([[4.2702, 2.1513, 1.3428]])
t3_plus3 : tensor([[ 2.1347,  4.0381, -3.1737]])
------------------------------
t4 : tensor([[10.0326,  8.0829],
        [11.1867,  8.9653],
        [11.6391,  9.4500]])
t5 : tensor([0.0000, 2.5000, 5.0000])
------------------------------
t5_plus1 : tensor([5.0000, 2.5000, 0.0000])
t5_plus2 : tensor([5., 5., 5.])
------------------------------
t6 : tensor([0, 1, 2, 3, 4])
------------------------------
t6_plus1 : tensor([1, 2, 3, 4])
t6_plus2 : tensor([5, 4, 3, 2])
------------------------------
##############################
random1 : tensor([[0.3126, 0.3791, 0.3087

### 해석
- torch.randint() : 지정된 범위 내에서 무작위 정수를 생성하는 함수
- t1의 low=10, high=20 : 10 이상 20 미만
- torch.rand() : 기본적으로 0.0 이상 1.0 미만에서 균등 분포를 기준으로 난수를 생성
- torch.rand() * n : 0.0 이상 1.0 * n 미만에서 균등 분포를 기준으로 난수를 생성
- torch.rand() + m : 0.0 + m 이상 1.0 + m 미만에서 균등 분포를 기준으로 난수를 생성
- torch.randn() : 정규 분포에 따라 난수를 생성하는 함수. 기본적으로 평균은 0, 표준편차가 1이며, 대부분 -3 ~ +3 사이의 값이 출력됨.
- torch.randn() * std : 표준편차가 std인 정규 분포
- torch.randn() + mean : 평균이 mean인 정규 분포
- torch.normal() : 정규 분포에 따라 난수를 생성하는 함수. torch.randn()과 달리 직접 평균과 표준편차를 지정해줘야 함. t4에서 mean이 평균, std가 표준편차를 지정해주는 값임.
- torch.linspace() : 시작값과 끝값을 균등하게 나누어 결과값을 출력함. t5에서 시작값이 0.0, 끝값이 5.0에서 3분할로 나누었으므로, [0.0,2.5,5.0]의 결과가 나온다.
- torch.arange(n) : 기본적으로 0 이상 n 미만의 정수를 출력하는 함수.
- torch.manual_seed() : 시드를 기반으로 난수를 만들며, 같은 시드를 설정하면 항상 같은 순서와 같은 난수를 생성한다. random1과 random3, random2와 random4의 출력 결과값이 같다는 것이 이를 알려준다. 머신러닝, 딥러닝에서 같은 모델을 여러 번 돌릴 때, 결과가 달라지면 문제가 생길 수 있다. 이에 실험 재현, 디버깅, 결과 비교에 시드 고정은 필수이므로 이 함수가 중요하다.

### 코드 추가
- 추가된 코드를 구분하기 위해 print("-" * 30)을 추가했다.
- torch.rand()의 범위를 바꾸는 방법과 결과 이해를 위해 t2_plus1~3에 관한 코드를 추가했다.
- torch.randn()의 범위를 바꾸는 방법과 결과 이해를 위해 t3_plus1~3에 관한 코드를 추가했다.
- torch.linspace()의 시작값과 끝값이 달라지는 방향에 따른 결과를 이해하기 위해 t5_plus1~2에 관한 코드를 추가했다.
- torch.arrange()에서 시작값, 끝값, 간격 지정에 따라 달라지는 결과를 이해하기 위해 t6_plus1~2에 관한 코드를 추가했다.
- 결과의 명확성을 추가하기 위해 print() 안에 코드 일부를 추가했다.

### 취득한 기술적 사항/고찰 내용
- rand(), randn() 함수에 연산자가 추가되었을 때 나타나는 결과
- 같은 시드를 설정하면 항상 같은 순서와 같은 난수를 생성하는 점

## e_tensor_type_conversion.py

In [17]:
import torch

a = torch.ones((2, 3))
print("a.dtype :",a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print("-" * 30)
print("a :",a)
print("-" * 30)
print("b :",b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print("c :",c)

d = b.to(torch.int32)
print("d :",d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

print("-" * 30)
print("double_d.dtype :",double_d.dtype)
print("short_e.dtype :",short_e.dtype)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

print("double_d.dtype :",double_d.dtype)
print("short_e.dtype :",short_e.dtype)

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

print("double_d.dtype :",double_d.dtype)
print("short_e.dtype :",short_e.dtype)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print("-" * 30)
print("double_d.dtype :",double_d.dtype)
print("short_e.dtype :",short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


a.dtype : torch.float32
------------------------------
a : tensor([[1., 1., 1.],
        [1., 1., 1.]])
------------------------------
b : tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
c : tensor([[15.8734,  4.0635,  5.6361],
        [11.7664,  0.4109,  0.7274]], dtype=torch.float64)
d : tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
------------------------------
double_d.dtype : torch.float64
short_e.dtype : torch.int16
double_d.dtype : torch.float64
short_e.dtype : torch.int16
double_d.dtype : torch.float64
short_e.dtype : torch.int16
------------------------------
double_d.dtype : torch.float64
short_e.dtype : torch.int16
torch.float64


### 해석
- torch.ones()는 텐서의 값을 모두 1.0으로 설정한다. 즉, 기본적으로 dtype은 float32이다. 함수 안에 dtype을 따로 설정할 수 있다. 이는 b에 관한 코드를 보면 알 수 있다.
- torch.rand() * n : 0.0 이상 1.0 * n 미만에서 균등 분포를 기준으로 난수를 생성
- torch.rand() 또한 dtype를 따로 설정할 수 있다.
- .to() : 데이터 타입, 디바이스(CPU/GPU), layout 등을 변경할 수 있는 함수
- double_d와 관련된 코드는 float64 형태를, short_e와 관련된 코드는 int16 형태로 텐서를 생성하는 걸 보여준다.
- 서로 다른 dtype을 연산하면 더 정밀한 쪽으로 변환된다. 

### 코드 추가
- 추가된 코드를 구분하기 위해 print("-" * 30)을 추가했다.
- 결과의 명확성을 추가하기 위해 print() 안에 코드 일부를 추가했다.
- a와 b의 출력값을 비교하기 위해 print(a)를 추가했다.
- double_d와 short_e의 타입이 정확히 나오는지 확인하기 위해 print()문을 추가했다.

### 취득한 기술적 사항/고찰 내용
- 텐서 자체의 결과는 tensor()로 결과가 출력되고, 텐서의 특징과 관련된 결과는 torch로 출력되는 점

## f_tensor_operations.py

In [1]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### 해석
- torch.add()는 element-wise 덧셈으로 t3[i][j] = t1[i][j] + t2[i][j] 방식으로 작동하며, 두 텐서의 덧셈 '+'도 같은 방식으로 작동한다.
- torch.sub()는 element-wise 뺄셈으로 t5[i][j] = t1[i][j] - t2[i][j] 방식으로 작동하며, 두 텐서의 뺄셈 '-'도 같은 방식으로 작동한다.
- torch.mul()는 element-wise 곱셈으로 t7[i][j] = t1[i][j] * t2[i][j] 방식으로 작동하며, 두 텐서의 곱셈 '*'도 같은 방식으로 작동한다.
- torch.div()는 element-wise 나눗셈으로 t9[i][j] = t1[i][j] / t2[i][j] 방식으로 작동하며, 두 텐서의 나눗셈 '/'도 같은 방식으로 작동한다.
- 위 네 개의 함수 모두 Element-wise operations과 Broadcasting을 가지고 있다.

### 취득한 기술적 사항/고찰 내용
- 함수를 간단한 연산자로 줄여쓰는 게 코드를 보기 편하다는 점

## g_tensor_operations_mm.py

In [5]:
import torch

t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())
print("-" * 30)
print(t7[0])

tensor(7) torch.Size([])
tensor([[-1.9101,  0.6684],
        [ 1.4764, -0.9888]]) torch.Size([2, 2])
torch.Size([10, 3, 5])
------------------------------
tensor([[-1.5126,  2.3840,  1.1192,  0.9393,  0.8394],
        [-2.6540, -2.3992, -2.5322,  1.2110,  0.6262],
        [-2.1623, -0.6121, -1.0223,  1.5126,  1.9039]])


### 해석
- torch.dot()은 1차원 벡터 내적으로 x=(a,b), y=(c,d)일 때 result = a*c + b*d로 결과값은 스칼라, 즉 크기가 없는 0차원 텐서로 나타난다.
- torch.mm()은 2차원 텐서의 행렬 곱셈으로 n×m 크기의 텐서와, m×p 크기의 텐서가 있으면 nxp 크기의 텐서 결과값이 나타난다.
- 위 코드의 torch.mm()에서 각 원소의 곱셈 : t4[0][0] = t2[0] 벡터와 t3의 0번 열 벡터의 내적, t4[0][1] = t2[0] 벡터와 t3의 1번 열 벡터의 내적 등 방식으로 계산된다.
- torch.bmm()은 3차원 텐서의 배치 행렬 곱셈으로 b×n×m 크기의 텐서와, b×m×p 크기의 텐서가 있으면 b×n×p 크기의 텐서 결과값이 나타난다.
- 위 코드의 torch.bmm()에서 각 원소의 곱셈 : for i in range(10): t7[i] = torch.mm(t5[i], t6[i]) 방식으로 계산된다.

### 코드 추가
- torch.bmm()의 결과값 텐서의 원소를 확인해보기 위해 print()문을 추가했다.
- 추가된 코드를 구분하기 위해 print("-" * 30)을 추가했다.

### 취득한 기술적 사항/고찰 내용
- n×m 크기의 텐서와, m×p 크기의 텐서가 있으면 nxp 크기의 텐서 결과값
- b×n×m 크기의 텐서와, b×m×p 크기의 텐서가 있으면 b×n×p 크기의 텐서 결과값

## h_tensor_operations_matmul.py

In [6]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


### 해석
- torch.matmul()은 다차원 텐서 행렬 곱을 유연하게 처리할 수 있는 함수로, dot product, matrix-vector product, matrix-matrix product(mm), batch-matrix-matrix product(bmm)를 자동으로 처리할 수 있다.
- 배열 끝에 있는 크기 1 차원은 자동으로 생략해서 취급

### 취득한 기술적 사항/고찰 내용
- 배열 끝에 있는 크기 1 차원은 자동으로 생략해서 취급

## i_tensor_broadcasting.py

In [10]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(f"{t1} * {t2} = ")
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(f"{t3} - {t4} =")
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(f"{t5} + 2.0 =")  # t5.add(2.0)
print(t5 + 2.0)  # t5.add(2.0)
print(f"{t5} - 2.0 =")
print(t5 - 2.0)  # t5.sub(2.0)
print(f"{t5} * 2.0 =")
print(t5 * 2.0)  # t5.mul(2.0)
print(f"{t5} / 2.0 =")
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


tensor([1., 2., 3.]) * 2.0 = 
tensor([2., 4., 6.])
################################################## 1
tensor([[ 0,  1],
        [ 2,  4],
        [10, 10]]) - tensor([4, 5]) =
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[1., 2.],
        [3., 4.]]) + 2.0 =
tensor([[3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.]]) - 2.0 =
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[1., 2.],
        [3., 4.]]) * 2.0 =
tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]]) / 2.0 =
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
tor

### 해석
- Element-wise operations과 Broadcasting 예시를 보여주는 것으로 + - * / 연산자와 add/sub/mul/div 메서드는 동일 동작한다는 점도 보여준다.
- normalize 함수는 텐서의 모든 원소를 255로 나누는 정규화 함수 역할을 한다.
- 이미지 정규화(normalization)는 일반적인 RGB 이미지의 픽셀 값 범위를 0-255에서 0-1 사이로 스케일링하는 것이다.
- Broadcasting에서 두 차원이 같거나, 한쪽 차원의 크기가 1이면 작동할 수 있다. 예를 들어 [2,3]+[4,2] 크기의 계산은 오류가 발생한다.
- 누락된 앞쪽 차원이나 뒤쪽 차원의 크기를 1로 간주해 맞춘다.
- torch.pow()는 원소별 거듭제곱의 함수이며, element-wise과 Broadcasting을 지원한다. ** 연산자가 이와 같은 표현이다.

### 코드 추가
- 결과의 명확성을 추가하기 위해 print() 안에 코드 일부를 추가했다.

### 취득한 기술적 사항/고찰 내용
- 이미지 정규화(normalization)는 일반적인 RGB 이미지의 픽셀 값 범위를 0-255에서 0-1 사이로 스케일링하는 것
- Broadcasting에서 두 차원이 같거나, 한쪽 차원의 크기가 1이면 작동할 수 있는 것

## j_tensor_indexing_slicing.py

In [11]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


### 해석
- x[n]은 x 텐서의 (n+1) 행 전체를 의미한다.
- x[:, 1]에서 :은 모든 행, 1은 두 번째 열을 의미하고, x[:, -1]은 모든 행에서 마지막 열을 의미한다.
- x[n:]은 (n+1)번째 행부터 끝까지를 의미한다.
- z[:m]은 m번째 행까지를 의미한다.
- 즉 z[n:m]은 (n+1)번째 행부터 m번째 행까지를 의미한다.

### 취득한 기술적 사항/고찰 내용
- 이상 미만의 범위로 텐서의 인덱스를 가져오는 것

## k_tensor_reshaping.py

In [12]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 해석
- view()는 텐서의 데이터를 공유하면서 텐서의 크기를 재구성한다. 새로운 텐서의 총 요소 수는 원본과 같아야 하고, 메모리에서 연속적인(contiguous) 텐서에만 사용할 수 있다.
- reshape()는 view()와 비슷하게 텐서의 크기를 변경하지만, 데이터가 메모리에서 연속적이지 않아도 작동한다. 필요한 경우 데이터를 복사하여 새로운 메모리 공간에 재배치하므로, view()보다 유연하게 사용할 수 있다.
- squeeze()는 크기가 1인 차원을 없애는 함수로, 지정하지 않으면 모든 1 크기의 차원을 제거, 인덱스를 지정하면 특정 차원만 제거한다.
- unsqueeze()는 새로운 차원을 추가하여 텐서의 크기를 확장한다.
- flatten()은 텐서를 1차원 텐서로 평탄화하며, flatten(start_dim, end_dim)으로 원하는 구간만 펼칠 수 있다.
- permute()는 텐서의 차원 순서를 재배열한다.
- transpose()는 두 개의 차원 순서를 서로 바꾼다.
- t()는 transpose()의 단축형으로, 2차원 텐서에만 사용 가능하며 0번째와 1번째 차원을 서로 바꾼다.

### 취득한 기술적 사항/고찰 내용
- 메모리에서 연속적인(contiguous) 텐서에만 사용할 수 있는 함수와 아닌 함수가 있다는 사실

## l_tensor_concat.py

In [13]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

### 해석
- torch.cat() 함수는 인자로 주어진 텐서들을 특정 차원을 기준으로 합친다.
- torch.cat() 함수에서 지정된 차원을 제외한 모든 차원의 크기는 같아야 한다.
- torch.cat() 함수에서 새로운 텐서의 크기는 병합된 차원의 크기가 합쳐진 결과이다.

### 취득한 기술적 사항/고찰 내용
- torch.cat() 함수에서 지정된 차원을 제외한 모든 차원의 크기는 같아야 한다는 점

## m_tensor_stacking.py

In [14]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


### 해석
- torch.cat(tensors, dim)과 torch.stack(tensors, dim) 모두 텐서의 차원을 추가하는 함수이다.
- torch.stack()은 새로운 차원을 생성해서 여러 텐서를 쌓고, 모든 입력 텐서는 동일한 크기(shape)여야 한다.
- torch.cat()은 이미 존재하는 차원에서 이어붙인다. 지정된 차원을 제외한 나머지 모든 차원의 크기가 동일해야 한다.
- stack(t1, t2,dim)≡cat(unsqueeze(t1,dim),unsqueeze(t2,dim),dim)

### 취득한 기술적 사항/고찰 내용
- stack(t1, t2,dim)≡cat(unsqueeze(t1,dim),unsqueeze(t2,dim),dim)

## n_tensor_vstack_hstack.py

In [2]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])
print("-" * 50)
t19 = torch.dstack([t16, t17])
print(t19.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])
--------------------------------------------------
torch.Size([2, 2, 6])


### 해석
- torch.vstack()은 텐서를 수직으로 쌓는 함수로, 첫 번째 차원을 따라 torch.cat() 함수를 수행하는 것과 같다. 입력 텐서들은 첫 번째 차원을 제외한 나머지 모든 차원의 크기가 동일해야 한다.
- torch.hstack()은 텐서를 수평으로 쌓는 함수이며, 이는 두 번째 차원을 따라 torch.cat() 함수를 수행하는 것과 같다. 단, 1D 텐서의 경우 예외적으로 dim=0을 따른다.

### 코드 추가
- 텐서를 깊이로 쌓는 방법을 알기 위해 torch.dstack()에 관한 코드를 추가했다.
- 추가된 코드를 구분하기 위해 print("-" * 50)을 추가했다.

### 취득한 기술적 사항/고찰 내용
- vstack(), hstack(), dstack() 등 모두 torch.cat() 함수를 편리하게 사용하는 별칭 함수라는 점

## 숙제 후기
코드 블럭 단위가 아닌 코드 변수 단위로 공부를 시작하다보니 시간도 꽤 걸렸고, 다양한 방식으로 텐서를 다루려고 코드를 추가했다가 이후 추가한 내용과 비슷한 코드들이 등장해 코드 추가 범위에서 뺀 적도 많았다. 과제에서 생각보다 텐서를 다양하게 다루어서 코드 추가를 많이 할 필요가 없었고, 코드 블럭 단위로 공부하는 게 더 효율적이라는 점을 이후 깨닫게 되고 과제 중반부부터는 코드 블럭 단위로 공부를 시작하게 됐다. 공부하면서 가장 신경 쓰였던 점은 결과 출력값에 tensor와 torch로 구분되어 출력된다는 점이었다.